#ifndef MANOCHIPER_H
#define MANOCHIPER_H

#include <stdint.h>
#include <stddef.h>

//----- Constants -----

/*
 * Cipher block size
 * It can be N*64 bit, 1 <= N <= 16, recommended min. 128 bits
 * The speed of encoding does not depend on the block size!
 */
#define CHIPER_BITS   256
#define CHIPER_BYTES  (CHIPER_BITS / 8)
#define CHIPER_QWORDS (CHIPER_BITS / 64)

/*
 * Key derivation (ChiperInit) working buffer size in bytes.
 * Larger = more memory-hard = harder GPU brute-force attack.
 * Must be >= 256. Recommended: 1MB = 1048576.
 * Can be overridden at compile time: -DCHIPER_KDF_MEM=4194304
 */
#ifndef CHIPER_KDF_MEM
#define CHIPER_KDF_MEM (1024 * 1024)   /* 1 MB default */
#endif

/*
 * Key derivation iteration count.
 * Higher = slower brute-force. Tune so ChiperInit takes e.g. 200 ms.
 * Can be overridden at compile time: -DCHIPER_KDF_ITER=20
 * Note that higher CHIPER_KDF_MEM makes slower too
 */
#ifndef CHIPER_KDF_ITER
#define CHIPER_KDF_ITER 4
#endif

/*
 * Salt size in bytes (for key derivation and CTR mode counter block).
 * Must be >= CHIPER_BYTES.
 */
#define CHIPER_SALT_BYTES CHIPER_BYTES

//----- Cipher mode -----

typedef enum {
	CHIPER_MODE_OFB = 0,   /* Output Feedback Mode */
	CHIPER_MODE_CTR = 1    /* Counter Mode (recommended) */
} ChiperMode;

//----- Data types -----

/*
 * Stream Cipher data structure.
 * Initialize with ChiperInit(), then use ChiperStreamEncode().
 * Reset with ChiperReset() (but avoid reset if not needed)
 */
typedef struct {
	uint8_t  sbox[512];              /* secret, key-derived S-box (doubled for speed) */
	uint64_t key[CHIPER_QWORDS];     /* secret key derived from password + salt */
	uint64_t block[CHIPER_QWORDS];   /* current keystream block */
	uint64_t counter[CHIPER_QWORDS]; /* CTR mode counter (unused in OFB) */
	size_t   block_bytepos;          /* current byte position in keystream block */
	ChiperMode mode;                 /* cipher mode: OFB or CTR */
} ChiperData;

//-------- API --------

/*
 * ChiperGenerateSalt
 *   Generate a cryptographically random salt.
 *   Must be called by the sender (Alice) before ChiperInit.
 *   The salt is NOT secret but must be unique per session.
 *   Transmit the salt to the receiver (Bob) in plaintext before encrypted data.
 *
 *   salt:     output buffer, must be CHIPER_SALT_BYTES long
 *   returns:  0 on success, -1 on failure (no random source available)
 */
int ChiperGenerateSalt(uint8_t *salt);

/*
 * ChiperInit
 *   Derive secret key and S-box from password + salt, then reset stream.
 *   Both sender and receiver call this with the same password and salt
 *   to arrive at identical cipher state.
 *
 *   data:       output, initialized cipher data structure
 *   psw:        input, password string (may be NULL or empty, but insecure)
 *   len:        input, length of psw in bytes (if <= 0: strlen is used)
 *   salt:       input, random salt (CHIPER_SALT_BYTES), generated by ChiperGenerateSalt
 *   mode:       input, CHIPER_MODE_OFB or CHIPER_MODE_CTR
 *   returns:    0 on success, -1 on memory allocation failure
 */
int ChiperInit(ChiperData *data, const char *psw, const int len,
			   const uint8_t *salt, ChiperMode mode);

/*
 * ChiperReset
 *   Reset the keystream to the beginning (same key and S-box, fresh stream).
 *   Call before starting a new message with the same key.
 *   Note: Reusing key+salt without changing either is dangerous in OFB mode.
 *         In CTR mode the counter is reset to zero.
 *
 *   data: input/output, cipher data structure (must be initialized)
 */
void ChiperReset(ChiperData *data);

/*
 * ChiperStreamEncode
 *   Encrypt (or decrypt) a buffer in-place.
 *   Encryption and decryption are the same operation (XOR stream cipher).
 *
 *   data:   input/output, cipher data structure
 *   buffer: input/output, plaintext in / ciphertext out (or vice versa)
 *   len:    length of buffer in bytes
 */
void ChiperStreamEncode(ChiperData *data, void *buffer, size_t len);

/*
 * ChiperPasswordScramble
 *   Scramble (deterministically) a string using default core alogrithm
 *   Recommended using ASAP on the password string before Init
 *   psw:     input/output, null-terminated string
 */
void ChiperPasswordScramble(char *psw);

#endif /* MANOCHIPER_H */
